name: Build and push OIBL ostree

on:
  workflow_dispatch:
  schedule:
  - cron: '00 00 * * *'
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: build-push-ostree
      env:
        QUAYUSERNAME: ${{ secrets.QUAYUSERNAME }}
        QUAYPASSWORD: ${{ secrets.QUAYPASSWORD }}
      run: make build-push-ostree REGUSER=$QUAYUSERNAME REGPASS=$QUAYPASSWORD
